name = "CoverRanges"
uuid = "cd865e0b-44d0-48f8-9b12-fb1d20898ca1"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
